"""
SafeCampus — Cyberbullying & Suicide Prevention Reporting Portal
Streamlit UI for Review 2

Run:
    pip install streamlit lime contractions emoji joblib scikit-learn nltk
    streamlit run safecampus_app.py

Expects 'models/' folder (generated by running the notebook first):
    models/tfidf.pkl
    models/<best_model_name>.pkl
    models/tfidf_multi.pkl   (optional, for bully-type prediction)
    models/lr_multi.pkl      (optional)
    models/meta.json
"""

import os, re, json, time
from datetime import datetime

import streamlit as st
import numpy as np
from transformers import pipeline

import nltk
nltk.download("stopwords", quiet=True)
nltk.download("wordnet",   quiet=True)
nltk.download("omw-1.4",   quiet=True)
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

import emoji as emoji_lib
import contractions

# ── Page config ─────────────────────────────────────────────────────────────
st.set_page_config(
    page_title="SafeCampus — Cyberbullying Reporting Portal",
    page_icon="🛡️",
    layout="centered",
)

# ── Shared NLP objects ───────────────────────────────────────────────────────
_stop       = set(stopwords.words("english"))
_lemmatizer = WordNetLemmatizer()

# ── Text cleaning (same as notebook) ────────────────────────────────────────
def _expand_contractions(text):
    try:
        return contractions.fix(text)
    except Exception:
        return text

def _correct_elongated(text):
    return re.sub(r"(\w)\1{2,}", r"\1", text)

def clean_text_v2(s: str) -> str:
    s = emoji_lib.replace_emoji(str(s), replace=" ")
    s = _expand_contractions(s)
    s = s.lower()
    s = re.sub(r"http\S+", " ", s)
    s = re.sub(r"@\w+",   " ", s)
    s = re.sub(r"#",       " ", s)
    s = re.sub(r"[^a-z0-9\s]", " ", s)
    s = _correct_elongated(s)
    s = re.sub(r"\s+", " ", s).strip()
    tokens = [
        _lemmatizer.lemmatize(tok)
        for tok in s.split()
        if tok not in _stop and len(tok) > 1
    ]
    return " ".join(tokens)

# ── Severity lexicon ─────────────────────────────────────────────────────────
TIER1_INSULT = {
    "stupid","idiot","loser","dumb","ugly","fat","moron",
    "useless","pathetic","trash","scum","hate you","freak",
}
TIER2_THREAT = {
    "kill you","beat you","hurt you","destroy you",
    "fight you","i will find you","watch your back","make you pay",
}
TIER3_SELF_HARM = {
    "kill myself","end it all","want to die","suicide","suicidal",
    "no reason to live","cant go on","better off dead",
    "end my life","not worth living","disappear forever",
    "everyone hates me","nobody cares","worthless","no point living",
}
TIER_RAGGING_MILD = {
    "fresher", "junior", "assignment", "intro de", "intro",
    "sir bol", "dance kar", "gaana ga", "canteen se", "senior"
}
TIER_RAGGING_SEVERE = {
    "hostel room aaja", "murga", "kapde nikal", "strip",
    "ragging", "police", "principal", "will complain", "maar", "peet",
    "baap", "mms"
}

def severity_score(text: str, model_prob: float) -> float:
    s     = str(text).lower()
    score = 0.5 * model_prob
    if any(w in s for w in TIER1_INSULT)    : score += 0.15
    if any(w in s for w in TIER2_THREAT)    : score += 0.25
    if any(w in s for w in TIER_RAGGING_MILD) : score += 0.15
    if any(w in s for w in TIER_RAGGING_SEVERE) : score += 0.35
    if any(p in s for p in TIER3_SELF_HARM) : score += 0.50
    return round(min(score, 1.0), 4)

def get_flags(text: str) -> list:
    s, flags = str(text).lower(), []
    if any(w in s for w in TIER1_INSULT)    : flags.append("Insult / Harassment")
    if any(w in s for w in TIER2_THREAT)    : flags.append("Direct Threat")
    if any(w in s for w in TIER_RAGGING_MILD) : flags.append("Academic / Hierarchy Abuse")
    if any(w in s for w in TIER_RAGGING_SEVERE): flags.append("Severe Ragging / Hazing")
    if any(p in s for p in TIER3_SELF_HARM) : flags.append("Suicide / Self-harm Risk")
    return flags or ["None detected"]

# ── Model loader (cached) ────────────────────────────────────────────────────
@st.cache_resource
def load_models():
    try:
        # We load a fine-tuned DistilBERT explicitly for toxicity
        # It's fast and context-aware.
        tox_pipeline = pipeline("text-classification", model="martin-ha/toxic-comment-model", tokenizer="martin-ha/toxic-comment-model")
        return tox_pipeline
    except Exception as e:
        print(f"Error loading model: {e}")
        return None

# ── Full prediction ──────────────────────────────────────────────────────────
def predict_full(text, tox_pipeline):
    cleaned  = clean_text_v2(text)
    
    if tox_pipeline is None:
        return {"prediction": "Error", "probability": 0, "severity": 0, "severity_raw": 0, "flags": [], "bully_type": None, "cleaned_text": cleaned}
        
    # Run through transformer pipeline (Truncation handles texts > 512 tokens)
    result   = tox_pipeline(cleaned, truncation=True, max_length=512)[0]
    
    # martin-ha/toxic-comment-model returns {"label": "toxic"/"non-toxic", "score": float}
    if result["label"] == "toxic":
        prob = float(result["score"])
    else:
        prob = 1.0 - float(result["score"])
        
    sev      = severity_score(text, prob)
    flags    = get_flags(text)

    bully_type = None

    return {
        "prediction"  : "Cyberbullying" if prob > 0.5 else "Safe",
        "probability" : round(prob * 100, 1),
        "severity"    : round(sev  * 100, 1),
        "severity_raw": sev,
        "flags"       : flags,
        "bully_type"  : bully_type,
        "cleaned_text": cleaned,
    }

# ── LIME explanation ──────────────────────────────────────────────────────────
def get_lime_words(text, tox_pipeline, n=15):
    try:
        from lime.lime_text import LimeTextExplainer
        def proba_fn(texts):
            cleaned = [clean_text_v2(t) for t in texts]
            results = tox_pipeline(cleaned, truncation=True, max_length=512)
            
            probs = []
            for res in results:
                if res["label"] == "toxic":
                    p = float(res["score"])
                else:
                    p = 1.0 - float(res["score"])
                probs.append([1.0 - p, p])
            return np.array(probs)
            
        exp = LimeTextExplainer(class_names=["Safe","Bully"]).explain_instance(
            text, proba_fn, num_features=n, num_samples=50 # Reduced to 50 for speed with BERT
        )
        return exp.as_list()
    except Exception as e:
        print("LIME failure:", e)
        return []

# ── CSS ───────────────────────────────────────────────────────────────────────
st.markdown("""
<style>
    .report-box {
        background: #1e1e2e;
        border: 1px solid #444466;
        border-radius: 10px;
        padding: 1.2rem 1.5rem;
        font-family: monospace;
        font-size: 0.88rem;
        white-space: pre-wrap;
        line-height: 1.7;
        color: #e0e0f0 !important;
    }
    .badge-critical { background:#fee2e2; color:#991b1b; padding:4px 10px;
                      border-radius:6px; font-weight:600; }
    .badge-high     { background:#fef3c7; color:#92400e; padding:4px 10px;
                      border-radius:6px; font-weight:600; }
    .badge-moderate { background:#dbeafe; color:#1e40af; padding:4px 10px;
                      border-radius:6px; font-weight:600; }
    .badge-low      { background:#dcfce7; color:#14532d; padding:4px 10px;
                      border-radius:6px; font-weight:600; }
    .section-head { font-size:0.75rem; font-weight:600; color:#6b7280;
                    text-transform:uppercase; letter-spacing:.05em; margin-bottom:4px; }
</style>
""", unsafe_allow_html=True)

# ── Load models ───────────────────────────────────────────────────────────────
tox_pipeline = load_models()

models_ok = tox_pipeline is not None

# ═══════════════════════════════════════════════════════════════════════════════
#  SIDEBAR
# ═══════════════════════════════════════════════════════════════════════════════
with st.sidebar:
    st.image("https://img.icons8.com/color/96/shield.png", width=60)
    st.title("SafeCampus")
    st.caption("Anti-Ragging, Cyberbullying & Suicide Prevention Portal")
    st.markdown("---")

    page = st.radio("Navigate", ["📋 Report Incident",
                                  "🔍 Analyze Text",
                                  "📊 Model Info",
                                  "ℹ️ How It Works"])

    st.markdown("---")
    st.markdown("**Emergency helplines 🇮🇳**")
    st.markdown("Anti-Ragging: `1800-180-5522`")
    st.markdown("iCall: `9152987821`")
    st.markdown("Vandrevala: `1860-2662-345`")
    st.markdown("iCall Chat: [icallhelpline.org](https://icallhelpline.org)")

    if models_ok:
        st.markdown("---")
        st.success(f"Transformer loaded ✓\n\n"
                   f"**DistilBERT (toxic-comment-model)**\n\n"
                   f"Context-Aware Dense Architecture")
    else:
        st.error("⚠️ Model failed to load.\nEnsure `transformers` and `torch` are installed.")

# ═══════════════════════════════════════════════════════════════════════════════
#  PAGE 1 — REPORT INCIDENT (main portal)
# ═══════════════════════════════════════════════════════════════════════════════
if page == "📋 Report Incident":

    st.title("🛡️ SafeCampus Reporting Portal")
    st.markdown(
        "**You are safe here.** Paste the message(s) you received below. "
        "Our system will assess the severity and — if needed — automatically "
        "generate a formal report for the college anti-ragging cell / counselor. "
        "_You decide what gets submitted._"
    )
    st.info("🔒 **Privacy guarantee**: Your submission is processed on the server only when you click Analyze. "
            "Nothing is stored or shared without your consent.")

    st.markdown("---")

    # ── Input form ───────────────────────────────────────────────────────────
    col1, col2 = st.columns([3, 1])
    with col1:
        student_name = st.text_input("Your name (optional — leave blank to stay anonymous)")
    with col2:
        anonymous = st.checkbox("Submit anonymously", value=True)

    message_input = st.text_area(
        "Paste the bullying message(s) here",
        height=160,
        placeholder="Example:\n'You're such a loser, nobody wants you in this group. "
                    "You should just disappear.'",
    )

    show_lime = st.checkbox("Show word-level explanation (LIME)", value=True)

    analyze_btn = st.button("🔍 Analyze & Generate Report", type="primary",
                             disabled=not models_ok)

    if analyze_btn and message_input.strip():
        with st.spinner("Analyzing message..."):
            time.sleep(0.4)   # small pause for UX
            result = predict_full(message_input, tox_pipeline)

        sev_pct = result["severity"]
        sev_raw = result["severity_raw"]
        ts      = datetime.now().strftime("%d %b %Y, %I:%M %p")
        submitter = "Anonymous" if (anonymous or not student_name.strip()) else student_name.strip()

        # ── Risk level & action ───────────────────────────────────────────
        if sev_raw >= 0.75:
            risk_label  = "CRITICAL"
            badge_class = "badge-critical"
            action_text = "🚨 Immediate counselor alert will be sent. A counselor will contact you within 15 minutes."
            counselor_notified = True
        elif sev_raw >= 0.50:
            risk_label  = "HIGH"
            badge_class = "badge-high"
            action_text = "⚠️ Formal complaint drafted below. Review it and click Submit to send to the counselor."
            counselor_notified = False
        elif sev_raw >= 0.25:
            risk_label  = "MODERATE"
            badge_class = "badge-moderate"
            action_text = "ℹ️ Report logged. Self-help and peer support resources provided below."
            counselor_notified = False
        else:
            risk_label  = "LOW"
            badge_class = "badge-low"
            action_text = "✅ Low severity detected. Self-help resources are available if needed."
            counselor_notified = False

        # ── Results dashboard ─────────────────────────────────────────────
        st.markdown("---")
        st.subheader("Analysis Result")

        m1, m2, m3 = st.columns(3)
        m1.metric("Classification", result["prediction"])
        m2.metric("Bullying probability", f"{result['probability']}%")
        m3.metric("Severity score", f"{sev_pct}%")

        # Risk badge
        st.markdown(
            f"<div style='margin:10px 0'><span class='section-head'>Risk level</span><br>"
            f"<span class='{badge_class}'>{risk_label}</span></div>",
            unsafe_allow_html=True
        )

        # Flags
        st.markdown(f"<div class='section-head'>Detected flags</div>", unsafe_allow_html=True)
        for flag in result["flags"]:
            if "Suicide" in flag:
                bg, text = "#7f1d1d", "#fecaca"   # dark red bg, light red text
            elif "Ragging" in flag or "Hierarchy" in flag:
                bg, text = "#4c0519", "#ffe4e6"   # dark rose bg, light rose/pink text
            elif "Threat" in flag:
                bg, text = "#7c2d12", "#fed7aa"   # dark orange bg, light orange text
            else:
                bg, text = "#713f12", "#fef08a"   # dark yellow bg, light yellow text
            st.markdown(
                f"<span style='background:{bg};color:{text};padding:4px 12px;"
                f"border-radius:6px;font-size:0.85rem;font-weight:600;"
                f"margin-right:6px'>{flag}</span>",
                unsafe_allow_html=True
            )

        # Bully type (if multi-class model available)
        if result.get("bully_type") and result["prediction"] == "Cyberbullying":
            st.markdown(
                f"<div style='margin-top:10px'><span class='section-head'>Bullying type</span><br>"
                f"<code>{result['bully_type'].replace('_',' ').title()}</code></div>",
                unsafe_allow_html=True
            )

        st.markdown("---")
        st.markdown(f"**Recommended action:** {action_text}")

        # ── Severity progress bar ─────────────────────────────────────────
        sev_color = "#ef4444" if sev_raw >= 0.75 else "#f59e0b" if sev_raw >= 0.50 else "#3b82f6" if sev_raw >= 0.25 else "#22c55e"
        st.markdown(
            f"<div style='margin:10px 0'>"
            f"<div class='section-head'>Severity gauge</div>"
            f"<div style='background:#e5e7eb;border-radius:8px;height:14px;overflow:hidden'>"
            f"<div style='width:{sev_pct}%;background:{sev_color};height:100%;border-radius:8px;"
            f"transition:width .5s'></div></div>"
            f"<div style='font-size:0.75rem;color:#6b7280;margin-top:3px'>"
            f"0% — Low &nbsp;&nbsp;&nbsp; 25% — Moderate &nbsp;&nbsp;&nbsp; 50% — High &nbsp;&nbsp;&nbsp; 75%+ — Critical</div>"
            f"</div>",
            unsafe_allow_html=True
        )

        # ── LIME word explanation ─────────────────────────────────────────
        if show_lime:
            with st.expander("🔬 Word-level explanation (LIME)", expanded=True):
                st.caption(
                    "Red words pushed the model toward **Bullying**. "
                    "Green words pushed it toward **Safe**. "
                    "This is what makes the prediction transparent and trustworthy."
                )
                with st.spinner("Running LIME explanation..."):
                    lime_words = get_lime_words(message_input, tox_pipeline)
                if lime_words:
                    sorted_words = sorted(lime_words, key=lambda x: abs(x[1]), reverse=True)
                    html_parts = []
                    for word, weight in sorted_words:
                        intensity = min(int(abs(weight) * 600), 220)
                        if weight > 0:
                            bg = f"rgba(239,68,68,{abs(weight)*3:.2f})"
                            label = "→ Bully"
                        else:
                            bg = f"rgba(34,197,94,{abs(weight)*3:.2f})"
                            label = "→ Safe"
                        html_parts.append(
                            f"<div style='display:flex;align-items:center;gap:10px;"
                            f"padding:4px 8px;border-radius:6px;background:{bg};"
                            f"margin-bottom:4px;font-size:0.87rem'>"
                            f"<code style='min-width:120px'>{word}</code>"
                            f"<span style='color:#374151;font-size:0.75rem'>{weight:+.4f} {label}</span>"
                            f"</div>"
                        )
                    st.markdown("".join(html_parts), unsafe_allow_html=True)
                else:
                    st.info("LIME not available. Install with: pip install lime")

        # ── Auto-generated report ─────────────────────────────────────────
        report_text = (
            f"SAFECAMPUS — INCIDENT REPORT\n"
            f"{'='*48}\n"
            f"Timestamp       : {ts}\n"
            f"Submitted by    : {submitter}\n"
            f"{'='*48}\n"
            f"CLASSIFICATION  : {result['prediction']}\n"
            f"PROBABILITY     : {result['probability']}%\n"
            f"SEVERITY SCORE  : {sev_pct}%\n"
            f"RISK LEVEL      : {risk_label}\n"
            f"FLAGS           : {', '.join(result['flags'])}\n"
        )
        if result.get("bully_type"):
            report_text += f"BULLY TYPE      : {result['bully_type'].replace('_',' ').title()}\n"
        report_text += (
            f"{'='*48}\n"
            f"ORIGINAL MESSAGE:\n{message_input.strip()}\n"
            f"{'='*48}\n"
            f"ACTION TAKEN    : {action_text}\n"
            f"{'='*48}\n"
            f"SUPPORT RESOURCES:\n"
            f"  Anti-Ragging Helpline : 1800-180-5522\n"
            f"  iCall Helpline        : 9152987821\n"
            f"  Vandrevala Foundation  : 1860-2662-345\n"
            f"  iCall Chat             : https://icallhelpline.org\n"
            f"  Anti-Ragging Cell      : antiragging@college.edu\n"
            f"{'='*48}\n"
        )

        st.markdown("---")
        st.subheader("📄 Auto-Generated Incident Report")
        st.markdown(f"<div class='report-box' style='color:#e0e0f0 !important;'>{report_text}</div>", unsafe_allow_html=True)

        col_a, col_b = st.columns(2)
        with col_a:
            st.download_button(
                label="⬇️ Download Report",
                data=report_text,
                file_name=f"safecampus_report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.txt",
                mime="text/plain",
            )
        with col_b:
            if counselor_notified:
                st.error("🚨 Counselor notified automatically (CRITICAL level)")
            else:
                st.button("📧 Submit to Counselor", help="In a live deployment, this emails the report to the college counselor.")

        # ── Resources ─────────────────────────────────────────────────────
        if sev_raw >= 0.50:
            st.markdown("---")
            st.subheader("🆘 Immediate Support Resources")
            rc1, rc2 = st.columns(2)
            with rc1:
                st.error("**iCall — Free Counseling**\n📞 9152987821\nMon–Sat, 8am–10pm")
            with rc2:
                st.warning("**Vandrevala Foundation**\n📞 1860-2662-345\nAvailable 24/7")
        else:
            st.markdown("---")
            st.info("**Peer Support**: Talk to your college's Student Welfare office or a trusted friend. "
                    "You are not alone.")

    elif analyze_btn and not message_input.strip():
        st.warning("Please paste a message before clicking Analyze.")


# ═══════════════════════════════════════════════════════════════════════════════
#  PAGE 2 — ANALYZE TEXT (quick classifier, no report generation)
# ═══════════════════════════════════════════════════════════════════════════════
elif page == "🔍 Analyze Text":

    st.title("🔍 Quick Text Analyzer")
    st.caption("For testing the model on custom messages. Does not generate a formal report.")

    text_input = st.text_area("Enter any message to analyze", height=120,
                               placeholder="Type or paste a message here...")
    btn = st.button("Analyze", type="primary", disabled=not models_ok)

    if btn and text_input.strip():
        result = predict_full(text_input, tox_pipeline)

        col1, col2, col3, col4 = st.columns(4)
        col1.metric("Result",      result["prediction"])
        col2.metric("Probability", f"{result['probability']}%")
        col3.metric("Severity",    f"{result['severity']}%")
        if result.get("bully_type"):
            col4.metric("Bully type", result["bully_type"].replace("_"," ").title())

        st.markdown("**Flags detected:** " + " | ".join(result["flags"]))
        st.markdown(f"**Cleaned input:** `{result['cleaned_text']}`")

        # Batch demo
        st.markdown("---")
        st.markdown("**Try these examples:**")
        examples = [
            "You're such a loser, nobody likes you.",
            "I will make you regret this. Watch your back.",
            "I can't do this anymore. I just want to end it all.",
            "Great lecture today! See you all at the fest!",
        ]
        for ex in examples:
            r = predict_full(ex, tox_pipeline)
            emoji_icon = "🚨" if r["severity_raw"] >= 0.75 else "⚠️" if r["severity_raw"] >= 0.50 else "🟡" if r["severity_raw"] >= 0.25 else "✅"
            st.markdown(
                f"{emoji_icon} **{r['prediction']}** ({r['probability']}% | severity {r['severity']}%) "
                f"— _{ex[:60]}_"
            )


# ═══════════════════════════════════════════════════════════════════════════════
#  PAGE 3 — MODEL INFO
# ═══════════════════════════════════════════════════════════════════════════════
elif page == "📊 Model Info":

    st.title("📊 Model Performance")

    if not models_ok:
        st.error("Install torch and transformers to load the model.")
    else:
        st.markdown(f"**Engine:** `DistilBERT Context-Aware Transformer`")
        st.markdown(f"**Weights:** `martin-ha/toxic-comment-model`")
        st.markdown(f"**Dataset:** Fine-tuned on Jigsaw Toxic Comment Classification Challenge")

        c1, c2, c3 = st.columns(3)
        c1.metric("Context",  "Deep Bidirectional")
        c2.metric("Parameters", "~66 Million")
        c3.metric("LIME Status", "Supported")

        st.markdown("---")
        st.subheader("What each metric means")
        st.markdown("""
| Metric | What it measures | Why it matters here |
|---|---|---|
| **F1 Score** | Balance of precision & recall | We care about both catching bullying AND not over-flagging safe messages |
| **AUC-ROC** | How well model separates classes regardless of threshold | Higher = better ranking of bully vs. safe |
| **Accuracy** | % correct predictions | Least important when classes are imbalanced |
| **Recall** | % of actual bully cases caught | Critical — missing a bullying case is worse than a false alarm |
| **Precision** | % of flagged cases that are actually bullying | Matters for counselor trust — too many false alarms = ignored system |
        """)

        st.markdown("---")
        st.subheader("Review 2 Improvements over Review 1")
        st.markdown("""
| Component | Review 1 | Review 2 |
|---|---|---|
| Preprocessing | Basic (stopwords + lemmatize) | + Emoji removal, contraction expansion, elongated word correction |
| TF-IDF features | 8,000 | 10,000 |
| Evaluation | F1 + accuracy + confusion matrix | + AUC-ROC curves |
| Explainability | None | LIME word-level explanation |
| Multi-class | Not supported | Future-work demo added |
| Deployment | Notebook only | Streamlit SafeCampus portal |
| Suicide risk | Lexicon only | Tiered 3-level severity scoring |
        """)

        st.markdown("---")
        st.subheader("Future Work Roadmap")
        st.markdown("""
**Phase 1 (Next review):**
- Fine-tune DistilBERT — contextual embeddings will handle sarcasm and coded language that TF-IDF misses
- True multi-class classification (6 bullying types) so counselors know *what kind* of bullying is occurring

**Phase 2 (Medium term):**
- FastAPI backend so the model can be called from any chat platform via REST API
- Browser extension using the API — opt-in device-side monitoring (zero privacy concern)
- Email/SMS counselor alert integration

**Phase 3 (Long term):**
- Multi-modal detection: text + image (memes, screenshots) using CLIP or ViLT
- Temporal escalation tracking: if severity rises over 5+ messages in a thread, auto-escalate
- Hindi / Hinglish support using IndicBERT for Indian college social media
        """)


# ═══════════════════════════════════════════════════════════════════════════════
#  PAGE 4 — HOW IT WORKS
# ═══════════════════════════════════════════════════════════════════════════════
elif page == "ℹ️ How It Works":

    st.title("ℹ️ How SafeCampus Works")

    st.markdown("### The problem with surveillance-based approaches")
    st.warning(
        "We **cannot** and **should not** monitor private WhatsApp or Instagram groups. "
        "This would violate India's IT Act (2000) and the Right to Privacy "
        "(Puttaswamy judgment, 2017). It is also technically infeasible — "
        "WhatsApp uses end-to-end encryption."
    )

    st.markdown("### Our approach: Victim-initiated reporting")
    st.success(
        "The student comes to us **when they need help**. They paste the message. "
        "We analyze it, score the risk, and generate a formal report for them — "
        "removing the emotional burden of having to write a complaint themselves."
    )

    st.markdown("---")
    st.markdown("### System pipeline")
    st.markdown("""
```
Student receives bullying message (WhatsApp, Instagram, anywhere)
        ↓
Opens SafeCampus portal on their phone/laptop
        ↓
Pastes the message(s) — THEIR choice, THEIR consent
        ↓
NLP model analyzes:
    → Is it cyberbullying? (binary classifier)
    → What type? (multi-class: age/gender/religion/...)
    → How severe? (0–100% severity score)
    → Suicide/self-harm risk? (3-tier lexicon)
        ↓
    ┌─────────────────────────────────────────────────┐
    │ LOW (<25%)    → Self-help resources shown       │
    │ MODERATE      → Formal complaint drafted        │
    │ HIGH (>50%)   → Complaint drafted + counselor   │
    │ CRITICAL(>75%)→ Counselor auto-alerted 🚨       │
    └─────────────────────────────────────────────────┘
        ↓
Student downloads report or submits to counselor
```
    """)

    st.markdown("---")
    st.markdown("### Why this is better than surveillance")

    col1, col2 = st.columns(2)
    with col1:
        st.error("**Surveillance (wrong approach)**\n\n"
                 "- Monitors everyone, always\n"
                 "- Massive false positives\n"
                 "- Legal liability under IT Act\n"
                 "- Students move to other platforms\n"
                 "- No consent = no trust")
    with col2:
        st.success("**Victim-initiated (SafeCampus)**\n\n"
                   "- Student consents at the moment they need help\n"
                   "- 100% of reports are real complaints\n"
                   "- Fully legal — student shares their own messages\n"
                   "- Removes shame and effort barrier\n"
                   "- Complaint writes itself in 30 seconds")

    st.markdown("---")
    st.markdown("### Why underreporting is the real problem")
    st.info(
        "Studies show **70–80% of cyberbullying victims never report it**. "
        "The two main reasons are **shame** (having to explain it to a person) "
        "and **effort** (having to write a formal complaint). "
        "SafeCampus removes both barriers — the student talks to a machine, "
        "and the complaint is auto-generated. That is the real-world value of this project."
    )
